### ISSUE TITLE
Multiple content-type headers are sent on HTTP request

### ISSUE THREAD

**Issue by trevoro** [HelloFax/hellosign-nodejs-sdk#10]
Hello,

Submitting forms with v3 HEAD sets two values for `content-type`. They are currently being set using two different key values.

In most parts of the lib the header value `Content-Type` is set (note the uppercase), but later in the library, you're transposing header values from the form-data npm module which has a lower case `content-type` value set. Because of the way this works we end up with multiple content-type headers, and this breaks other things.

For example, I'm trying to get this to work with a other apps that do a lower case comparison on header values, as it's not part of the standard.

The fix is simple, but I wanted to make sure I knew which content-type value to accept;
Either `multipart/form-data; boundary=-.....` or
`application/x-www-form-urlencoded`.

Thanks

**Comment by trevoro** [comment]
See https://github.com/HelloFax/hellosign-nodejs-sdk/pull/11

**Comment by trevoro** [comment]
bump @renderf0x

**Comment by renderf0x** [comment]
Heya Trevor --

Thanks for catching this, and sorry it's causing you issues.

Looks like you already got a PR in for this, and skipping over the headers from the form as you're doing seems like a legit solution.
You've probably already reached this conclusion then, but we're already setting
`headers['Content-Type'] = 'application/x-www-form-urlencoded';`
in the `_setDefaultHeaders` method.

Looks good on your side, so I'll go ahead and merge your PR.

**Comment by renderf0x** [comment]
Merged #11

**Comment by trevoro** [comment]
Thanks! :+1:
