### ISSUE TITLE
OpenAPI: signatureRequestFiles() is returning a 'json' response making it challenging to save files

### ISSUE THREAD

**Issue by imonkia** [HelloFax/hellosign-nodejs-sdk#114]
In Legacy SDK, files could be saved using `fs` module, as such:

```javascript
var file = fs.createWriteStream("files.zip");
    response.pipe(file);
    file.on('finish', function() {
      file.close();
});
```

With OpenAPI, the above implementation returns: `pipe is not a function`. However, when the response is converted to a Buffer, a blank PDF is saved. This does not work with a ZIP file, the file will be corrupt.

`responseType` in responses (`res.response.config`) using OpenAPI SDK is set to `'json'`, which could be the reason files are corrupted when saved or saving blank.

A request using axios only (no SDKs), will save files successfully when `responseType: 'arraybuffer'` is sent in the request.

**Comment by jtreminio-dropbox** [comment]
Thanks! Fix is incoming, we're creating separate endpoints for downloading files as binary, getting file URL, and data uri. See https://github.com/hellosign/hellosign-openapi/pull/130

**Comment by jtreminio-dropbox** [comment]
See https://github.com/hellosign/hellosign-openapi/pull/130
