### ISSUE TITLE
List methods trigger 500 error when a search string with multiple parameters is provided

### ISSUE THREAD

**Issue by jminuscula** [HelloFax/hellosign-nodejs-sdk#12]
Following the documentation [1], I'm constructing and sending my search query as follows:

```
let queryParams = {
    to: signerEmail,
    title: titleKeyword,
    complete: complete ? 'true' : 'false',
};

let query = [];
for (let key in queryParams) {
    if (queryParams[key]) {
        query.push(key + ':' + queryParams[key].replace(/\s+/g, '+'));
    }
}

let searchQuery = query.join('+AND+);
return hellosign.signatureRequest.list({ query: searchQuery }); 
```

Which always triggers a 500 error. Intercepting the request URL on the SDK, I see that the request data is always urlencoded [2], which provides a URL of the form:

`"https://api.hellosign.com/v3/signature_request/list?query=to%3Aemail%40example.com%2BAND%2Btitle%3AKeyword"`

With the help of Hellosign support we discovered that the API fails when the "+" around the "AND" are encoded. On the other hand, if a query value has a "+" sign (as in email+one@example.com) the API will fail to parse the query, and thus return incorrect results.

It'd be nice to adapt the `list` methods to accept the query as an object, in which the developers can define the different filters. If the API is working as designed (in spite of the 500), it'd be nice if the nodejs request examples on the API reference showed how to construct the query correctly (issue #8)

Cheers!

[1] https://www.hellosign.com/api/reference#Search
[2] https://github.com/HelloFax/hellosign-nodejs-sdk/blob/v3/lib/utils.js#L46

**Comment by jminuscula** [comment]
Working with Alex in API support we have fixed this using spaces instead of "+" signs when building the query string —this makes sense, but I don't think it's clear from the search documentation.

I'm keeping this open in case you want to fix the 500 error. Thanks!

**Comment by renderf0x** [comment]
Hey @jminuscula -

Sorry for the delay, and glad you were able to work that out.

This basically comes down to a documentation issue for us -- we need specific examples for NodeJS and other SDKs instead of just cURL (and converting spaces to '+' is only relevant to cURL).

We'll make an action item to update the documentation for this internally.

Cheers!

//Derek

**Comment by jminuscula** [comment]
hey @renderf0x,

yeah, that's the understanding I got to with support. I think it'd be useful for users to return a 400 Bad Request instead of a 500 error —since this made me assume it was an API issue.

Thanks!
