### ISSUE TITLE
Typescript types appear to be out of date 

### ISSUE THREAD

**Issue by andrewtremblay** [HelloFax/hellosign-nodejs-sdk#121]
The types defined in `@types/hellosign-sdk` appear to reference 1.6, which is significantly different from more modern versions. 

I've added a PR to main types repo https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63512 to address the differences between 1.6 and 2.1 (namely the function default export) but it would be ideal if a hellosign employee maintained the types there or if it was moved into this package.

**Comment by jtreminio-dropbox** [comment]
The upcoming OpenAPI version is written in TypeScript: https://github.com/hellosign/hellosign-nodejs-sdk/tree/openapi/types

I believe the plan is to stop any further non-security development on the non-OpenAPI (legacy) SDK versions.
