### ISSUE TITLE
Is there a way to specify the page_size for list()?

### ISSUE THREAD

**Issue by thatjuan** [HelloFax/hellosign-nodejs-sdk#2]
There doesn't appear to be a way to retrieve multiple pages from .list() calls nor to set the page_size

**Comment by renderf0x** [comment]
Heya @thatjuan -

You should be able to specify pages / page size in the sdk by passing in an options object to that call like so:

``` javascript
hellosign.signatureRequest.list({page: 1, page_size: 15})
```

I think there needs to be better documentation around this, though – we should add this to the README for the SDK so it's obvious. I'll do that, and update this issue when done.

**Comment by renderf0x** [comment]
Added to the docs, closing.

Thanks for catching that @thatjuan !
