### ISSUE TITLE
Add support for Decline to Sign

### ISSUE THREAD

**Issue by desmondw** [HelloFax/hellosign-nodejs-sdk#20]
The following changes have been made to the API:
- There is a new parameter allow_decline for declining to sign signature requests
- There is a new API status_code for declined requests
- There is a new API variable is_declined on SignatureRequest objects
- There is a new API variable decline_reason on Signature objects

**Comment by npbee** [comment]
This is already supported by passing `allow_decline: true' as part of the options to signature request creation calls, e.g.

```js
const options = {
  allow_decline: true,
  // ...
};

hellosign.signatureRequest.sendWithTemplate(options)
 .then(function(res) {
    // ...
  });
```
