### ISSUE TITLE
Update dependencies to work with React Native

### ISSUE THREAD

**Issue by renderf0x** [HelloFax/hellosign-nodejs-sdk#22]
We make some calls to a few libraries that are incompatible with React Native ( `child_process` and `fs` for instance ) and others that need to be explicitly required for the dependency manager to find them (`http`, `https`).

Projects for React Native won't build with these dependencies missing.

**Comment by phillipwei** [comment]
How'd you end up solving this? By adding dependencies?

**Comment by alexmac05** [comment]
Hi Phillipwei,

Is this creating an issue for you?

**Comment by latoyazamill** [comment]
Hi @phillipwei - it has been some time and we are unsure if this issue has ben resolved for you. If it is, just know that we have worked with our Engineering team to prioritize goals for the SDK and this is on our long term road map. If we are to add this functionality, we will be sure to reopen the issue and solve accordingly.
