### ISSUE TITLE
Method Update Template files is not implemented

### ISSUE THREAD

**Issue by nilsonivano** [HelloFax/hellosign-nodejs-sdk#24]
Hi, 

I've noticed that this method form HS documentation (https://app.hellosign.com/api/reference#update_template_files) is not implemented on this sdk yet.

I'm using HS api on my application and would like to use this method.

**Comment by npbee** [comment]
Hi!  You're correct, that endpoint is not currently implemented but it should be fairly straightforward to implement.  I've put in an internal request for this and I'll keep the issue updated with any progress.  Thanks!

**Comment by clpacswe** [comment]
status check.

**Comment by abhijit-Amne** [comment]
any update on this ?

**Comment by omrips** [comment]
This is an important feature for my opinion, any progress on this?

**Comment by nathanbuchar** [comment]
Noted, I'll take a look. We're currently roadmapping a new version of the SDK so I'll be sure to include this in there if we can't squeeze it in beforehand :)

**Comment by latoyazamill** [comment]
this has been resolved in a recent PR: https://github.com/HelloFax/hellosign-nodejs-sdk/pull/65
