### ISSUE TITLE
Make response headers available

### ISSUE THREAD

**Issue by radhack** [HelloFax/hellosign-nodejs-sdk#27]
At this point, I can't see how to parse the response headers for rate limits:
https://app.hellosign.com/api/documentation#RateLimits
```
X-Ratelimit-Limit: 2000 
X-Ratelimit-Limit-Remaining: 1999 
X-Ratelimit-Reset: 1430170900
```
I believe we need to make them part of the _responseHandler in HelloSignResource.js

**Comment by jyoung488** [comment]
👍
