### ISSUE TITLE
Facing issue while integrating hellosign embedded request API using Node.js 

### ISSUE THREAD

**Issue by shridharbhande-tudip** [HelloFax/hellosign-nodejs-sdk#29]
Hi there,
We have our own template created and there is "Customer" role who will sign.
We have tried a lot to integrate hellosign embedded create request API using Node.js, but i was not able to create any request by using the same. So i tried with 'Curl' on terminal and successfully created embedded signature request id. I installed 'curlrequest' module to create request using curl, but i got following error response:

We tried with following code:

curl.request({
            url: 'https://api.hellosign.com/v3/signature_request/create_embedded_with_template',
            user: '--------------API key----------------------:',
            data: {
                client_id: '-----------------client id --------------------------------',
                template_id: '--------------------template id-----------------------',
                subject: 'My First embedded Signature Request',
                message: 'Awesome, right?',
                signers: [
                    {
                        email_address: '----------------email address------------------',
                        role: 'Customer',
                        name: 'Test'
                    }],
                test_mode: 1
            }
        }, function (err, parts) {
            console.log("================================", err, data);
        });

{"error":{"error_msg":"Malformed signers parameter(s)","error_name":"bad_request"}}

Please suggest, this is kinda urgent. What is wrong, or what is missing or how we can specify signers at least in the request?

Thanks.

**Comment by radhack** [comment]
Hi @shridharbhande-tudip,

I'd be glad to help! Please post the code snippet using the SDK that you're having an issue with, along with the error message, and let's take a look at what's up.

A working example would look something like this:

```
var hellosign = require('hellosign-sdk')({key: 'YOURAPIKEY'});
var options = {
    test_mode : 1,
    clientId : 'YOURCLIENTID',
    template_id : 'YOURTEMPLATEID',
    subject : 'Purchase Order',
    message : 'Glad we could come to an agreement.',
    signers : [
        {
            email_address : 'george@example.com',
            name : 'George',
            role : 'Client'
        }
    ],
    ccs : [
        {
            email_address :'accounting@example.com',
            role_name : "Accounting"
        }
    ],
    custom_fields : {
        Cost : '$20,000'
     }
};

hellosign.signatureRequest.createEmbeddedWithTemplate(options)
    .then(function(response){
        //parse response
    })
    .catch(function(err){
        //catch error
    });

```

**Comment by shridharbhande-tudip** [comment]
Thanks @redhack, we tried this and it's working now. Great help man.

Can you please guide us with this scenario: 

1. We are selling some services.
2. Some proposal gets created at the end.
3. We have created template for terms and condition page in hellosign.
4. Terms and condition page is the last one where we add sign.

Where we can specify the actual proposal where actual quotation for services is present? and also if we have any page with dynamic content (say we have total price on services page) and we want to add signature there, how we can do this?

Your help will will be greatly appreciated.

**Comment by radhack** [comment]
Glad that helped @shridharbhande-tudip! 

Let's move this over to apisupport@hellosign.com so we can get into the details of your documents/usecase privately - please write in when you have a moment.

It'd be helpful if you could describe the proposal document (or better yet, include an example of it) in greater detail in your email. Please also include any other documents that would be part of the packet of documents to be signed.

I'll keep an eye out for your email and we'll take it from there.

Thanks again!

**Comment by shridharbhande-tudip** [comment]
Thanks @redhack

As per your suggestion, we have sent a details mail regarding our all scenarios and please find attached PDF to that mail. Please reply on that mail ASAP.

Your help is highly appreciated.

Thanks.
