### ISSUE TITLE
MessageListener not being called

### ISSUE THREAD

**Issue by Natelegreat1** [HelloFax/hellosign-nodejs-sdk#33]
Hello.
For some reason, `messageListener` is not being called.
I am successfully seeing the document and able to sign it.
I have tried - unsuccessfully - to put eventListeners on the Window...
I am not sure what else to try?

```
const opts = {
      this.props.url,
      allowCancel: true,
      uxVersion: 2,
      messageListener: function(eventData) {
        console.log('hello!?')
        if (eventData.event === window.HelloSign.EVENT_SIGNED) {
          this.props.onSign(eventData['signature_id'])
        }
      }
    }
window.HelloSign.init('API_KEY')
window.HelloSign.open(opts)
```

**Comment by jyoung488** [comment]
Closing since the `HelloSign.open()` call is actually part of the client side code of the [HelloSign Embedded Signing workflow](https://app.hellosign.com/api/embeddedSigningWalkthrough#EmbeddedSigningClientSide)

[GitHub repo](https://github.com/HelloFax/hellosign-embedded)
