### ISSUE TITLE
Allow Response Handling with Delete Template Endpoint 

### ISSUE THREAD

**Issue by latoyazamill** [HelloFax/hellosign-nodejs-sdk#50]
const hellosign = require('hellosign-sdk')({ key: 'SIGN_IN_AND_CREATE_API_KEY_FIRST' });

hellosign.template.delete(templateId).then((res) => { 
// Handle response -------> NEVER GETS CALLED. 
}).catch((err) => { 
// Handle error 
});

Allow the response of 200 OK to get proper handling in the above block of code. At the moment nothing gets handled with the positive response.

**Comment by ayushnawani** [comment]
Any update on this issue?

**Comment by basherbar** [comment]
Bumping this issue
