### ISSUE TITLE
How can I set the merge_fields in sendWithTemplate option?

### ISSUE THREAD

**Issue by tpikachu** [HelloFax/hellosign-nodejs-sdk#55]
I'm using this nodejs-sdk to send the eSign document to users who attempts to register to our platform. But I should send them document with pre-filled form. Such as their name and email address and don't allow them to change this at document.
But seems **merge_fields** parameter is not working properly.

Any help please

**Comment by latoyazamill** [comment]
Hi @tpikachu Can you please write into apisupport@hellosign.com. We will need additional information to help you troubleshoot this very specific case. Thanks!
