### ISSUE TITLE
using pin number unclaimed draft throwing invalid param error.

### ISSUE THREAD

**Issue by slackincode** [HelloFax/hellosign-nodejs-sdk#6]
When using the `hellosign.unclaimedDraft.createEmbeddedWithTemplate` method with signers in the format:

```
    signers: [
        {
            name: 'Sherlock',
            role: 'Signer',
            email_address: 'sherlock@holmesdetective.co.uk',
            pin: 3645
        }
    ]
```

it works fine, however, if I try to use `hellosign.unclaimedDraft.createEmbedded` with the same signers. it breaks with an error of `Invalid parameter: 'pin'`.  I verified with Hellosign that this is indeed a bug and that it should work (and does work via CURL).  So it must be the node-sdk that is causing the error.

**Comment by renderf0x** [comment]
Ouf, thanks for the catch.

It doesn't look like we're processing this parameter explicitly -- could you post the whole call you're making (minus anything sensitive, of course) so we can verify?

Cheers!

**Comment by slackincode** [comment]
```
var hellosign = require('hellosign-sdk')({key: config.apiKey});

var options = { test_mode: 1,
                clientId: '-------------------',
                requester_email_address: 'sender@example.com',
                is_for_embedded_signing: 1,
                signers:
                 [ { email_address: 'reciever@example.com',
                     name: 'John Doe',
                     role: 'Client 1',
                     pin: '3333' } ],
                file_url: [ 'http://www.publishers.org.uk/_resources/assets/attachment/full/0/2091.pdf' ],
                use_preexisting_fields: 1 }

return hellosign.unclaimedDraft.createEmbedded(options)
  .then(function(response) {
    if (response.statusCode !== 200) {
      throw new Error('Error creating unclaimed draft');
    }

    return response.unclaimed_draft;
  })
```

**Comment by renderf0x** [comment]
Thanks for that -- I was able to confirm that this call has issues.

However, it's not due to the NodeJS SDK -- we're actually not expecting this parameter in any calls to create unclaimed drafts without a template.

I'll check whether this is intentional or an omission and get back.

**Comment by renderf0x** [comment]
@slackincode I think our API support team is messaging you about this as well, but it's an oversight for this not to be validated the same way in both endpoints. It's on the books to correct. Thanks for finding this!
