### ISSUE TITLE
Replace Request Lib

### ISSUE THREAD

**Issue by burn2delete** [HelloFax/hellosign-nodejs-sdk#67]
Request is deprecated and should be replaced with an alternative like fetch or node-fetch.

**Comment by latoyazamill** [comment]
Hi @flyboarder and thanks for reaching out! As of Feb 11th 2020, request is fully deprecated. No new changes are expected land. We've looked into information about why request is [deprecated](https://github.com/request/request/issues/3142) and will explore possible [alternatives](https://github.com/request/request/issues/3143). 

This GitHub issue will remain open until we refactor the NodeJS SDK with a request alternative in the future. 

Please be on the look out for any pull requests that are created to resolve this issue.

**Comment by thallada** [comment]
This package is causing a "High" npm vulnerability report because of `request`

![Screen Shot 2020-07-01 at 1 52 52 PM](https://user-images.githubusercontent.com/1505923/86276106-51d17900-bba2-11ea-824b-1d5d3cbdcae8.png)

**Comment by latoyazamill** [comment]
Hi @thallada We will prioritize this to be reviewed and resolved within the next quarter. Please be on the look out for any pull requests that are created to resolve this issue.

Thanks!
