### ISSUE TITLE
provide a proxy option

### ISSUE THREAD

**Issue by JaredCE** [HelloFax/hellosign-nodejs-sdk#68]
I need to use your library through a proxy, but there isn't an available proxy setting to input a proxy

As far as i can tell, you'd need to add the option: proxy (https://www.npmjs.com/package/request#requestoptions-callback) here:

https://github.com/HelloFax/hellosign-nodejs-sdk/blob/v3/lib/HelloSignResource.js#L390

And a way of setting it, probably in here:

https://github.com/HelloFax/hellosign-nodejs-sdk/blob/v3/lib/hellosign.js#L65

**Comment by latoyazamill** [comment]
Hi @JaredCE we'd love to know more about your use case. Please write into apisupport@hellosign.com and we will explore this in further details.

**Comment by latoyazamill** [comment]
I will reopen your ticket and do a more thorough analysis throughout the 3rd quarter. In the meanwhile, as you mentioned, you can use one of your favorite libraries such as [Node HTTP Proxy](https://github.com/http-party/node-http-proxy). 

Please be on the look out for any pull requests that are created to resolve this issue.

**Comment by JaredCE** [comment]
Should anyone else come across this issue: I found https://www.npmjs.com/package/global-agent works really well.

**Comment by latoyazamill** [comment]
Thank you so much for listing another option @JaredCE. As of now, we have worked with our Engineering team to prioritize goals for the SDK and this is on our long term road map. If we are to add this functionality, we will be sure to reopen the issue and solve accordingly.
