### ISSUE TITLE
Add Editable Merge Fields support

### ISSUE THREAD

**Issue by rmelencio** [HelloFax/hellosign-nodejs-sdk#7]
When updating the SDKs to include editable merge fields, please also update the SDK git repos README examples (if necessary) and the following in the API docs:
- "Send with Template" endpoint example
- "Send Embedded Signature Request with Template" endpoint example
- Templates Walkthrough
- Signature Request Walkthrough -> Using Templates

**Comment by npbee** [comment]
Editable merge fields are supported via the previously implemented support for `custom_fields`.  I've added an example in the readme here:  https://github.com/HelloFax/hellosign-nodejs-sdk#send-a-signature-request-with-template.
