### ISSUE TITLE
signatureRequest.cancel promise never resolves on success

### ISSUE THREAD

**Issue by alexortizl** [HelloFax/hellosign-nodejs-sdk#77]
hellosign-sdk version: 1.6.0 

Using the code snippet in the example: 

    hellosign.signatureRequest.cancel(request_id)
     .then(function(response){
      console.log(response.statusCode);
      console.log(response.statusMessage);
    })
    .catch(function(err){
      // Handle errors
    });

with a valid `request_id` successfully cancels the request but the promise is never resolved, in the example `console.log(response.statusCode);` and ` console.log(response.statusMessage);` are never called. An invalid `request_id` does reject the promise.

**Comment by hazemhamedhs** [comment]
Hi Alex,

Thanks for writing in and I hope this finds you well!

Kindly note that a successful call to this [endpoint](https://app.hellosign.com/api/reference#cancel_incomplete_signature_request) will return an **empty** 200 OK response if the signature request is eligible to be canceled and has been successfully queued.

This 200 OK response does not indicate a successful cancelation of the signature request itself. The cancelation is confirmed via the "**signature_request_canceled**" event. It is recommended that a [callback handler](https://app.hellosign.com/api/reference#Event) be implemented to listen for the "signature_request_canceled" event. This callback will be sent only when the cancelation has completed successfully. If a callback handler has been configured and the event has not been received within 60 minutes of making the call, check the status of the request in the API Dashboard and retry the cancelation if necessary.

To be eligible for cancelation, a signature request must have been sent successfully, must not yet have been signed by all signers, and you must either be the sender or own the API app under which it was sent. A partially signed signature request can be canceled.

I hope this help clear things up for you! Feel free to email us at apisupport@hellosign.com if you have any other questions or concerns.
