### ISSUE TITLE
TypeError: source.on is not a function 

### ISSUE THREAD

**Issue by ppichier** [HelloFax/hellosign-nodejs-sdk#94]
Hello ! I m new to HelloSign and i m trying to create an embedded signature request. But i ve got the following error:

`TypeError: source.on is not a function`

`
var options = {
  test_mode: 1,
  clientId:  MyClienId,
  title: "NDA with Acme Co.",
  subject: "The NDA we talked about",
  message:
    "Please sign this NDA and then we can discuss more. Let me know if you have any questions.",
  signers: [
    {
      email_address: "test@test.com",
      name: "Jill",
      order: 1,
    },
  ],
  attachments: [
    {
      name: "Example Name",
      instructions: "Example instructions",
      signer_index: 1,
      required: 1,
    },
  ],
  cc_email_addresses: ["test@test.com"],
  files: ["/dev.pdf"],
};

hellosign.signatureRequest
  .createEmbedded(options)
  .then(function (res) {
    console.log(res.signature_request);
  })
  .catch((err) => {
    console.log(err);
  });
`

I think this is because of the files array ?

**Comment by yarosz** [comment]
I'm running into the same issue with my files array, did you resolve it or repost your issue to a new location @ppichier?

**Comment by 8ctopotamus** [comment]
I am getting the same error just trying to use examples from the README. I would also like to know if you found a solution, @ppichier
